export const licenses = {
  cc0: {
    label: "CC0",
    href: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  ccBy: {
    label: "CC BY 3.0",
    href: "https://creativecommons.org/licenses/by/3.0/",
  },
  ccBySa: {
    label: "CC BY-SA 4.0",
    href: "https://creativecommons.org/licenses/by-sa/4.0/",
  },
} as const;

export type Player = {
  slug: string;
  name: string;
  fullName: string;
  number: string;
  position: string;
  role: string;
  group: "门将" | "防线" | "中场" | "锋线";
  image: string;
  photoPosition: string;
  photoContext: string;
  transitional?: boolean;
  credit: string;
  license: (typeof licenses)[keyof typeof licenses];
  source: string;
  profileHref?: string;
};

export const coreSquad: Player[] = [
  {
    slug: "alisson-becker",
    name: "Alisson",
    fullName: "Alisson Becker",
    number: "01",
    position: "门将",
    role: "最后防线 · 启动进攻",
    group: "门将",
    image: "/players/alisson.jpg",
    photoPosition: "50% 18%",
    photoContext: "利物浦到场",
    credit: "Timmy96",
    license: licenses.cc0,
    source: "https://commons.wikimedia.org/wiki/File:Alisson_Becker_04012026_(1).jpg",
    profileHref: "/players/alisson-becker",
  },
  {
    slug: "virgil-van-dijk",
    name: "Van Dijk",
    fullName: "Virgil van Dijk",
    number: "04",
    position: "中卫",
    role: "队长 · 防线指挥",
    group: "防线",
    image: "/players/van-dijk.jpg",
    photoPosition: "50% 18%",
    photoContext: "利物浦到场",
    credit: "Timmy96",
    license: licenses.cc0,
    source: "https://commons.wikimedia.org/wiki/File:Virgil_van_Dijk_06042025_(2).jpg",
  },
  {
    slug: "milos-kerkez",
    name: "Kerkez",
    fullName: "Milos Kerkez",
    number: "06",
    position: "左后卫",
    role: "高频推进 · 边路强度",
    group: "防线",
    image: "/players/kerkez.jpg",
    photoPosition: "82% 46%",
    photoContext: "利物浦比赛",
    credit: "Timmy96",
    license: licenses.cc0,
    source: "https://commons.wikimedia.org/wiki/File:Milos_Kerkez_04012026_(2).jpg",
  },
  {
    slug: "jeremie-frimpong",
    name: "Frimpong",
    fullName: "Jeremie Frimpong",
    number: "30",
    position: "右后卫",
    role: "纵深冲刺 · 宽度制造",
    group: "防线",
    image: "/players/frimpong.jpg",
    photoPosition: "50% 18%",
    photoContext: "利物浦训练",
    credit: "Timmy96",
    license: licenses.cc0,
    source: "https://commons.wikimedia.org/wiki/File:Jeremie_Frimpong_04012026_(3)_(cropped).jpg",
  },
  {
    slug: "ryan-gravenberch",
    name: "Gravenberch",
    fullName: "Ryan Gravenberch",
    number: "38",
    position: "中场",
    role: "抗压转身 · 中路衔接",
    group: "中场",
    image: "/players/gravenberch.jpg",
    photoPosition: "50% 16%",
    photoContext: "利物浦到场",
    credit: "Timmy96",
    license: licenses.cc0,
    source: "https://commons.wikimedia.org/wiki/File:Ryan_Gravenberch_06042025_(1).jpg",
  },
  {
    slug: "dominik-szoboszlai",
    name: "Szoboszlai",
    fullName: "Dominik Szoboszlai",
    number: "08",
    position: "中场",
    role: "压迫引擎 · 后排冲击",
    group: "中场",
    image: "/players/szoboszlai.jpg",
    profileHref: "/players/dominik-szoboszlai",
    photoPosition: "50% 13%",
    photoContext: "利物浦到场",
    credit: "Timmy96",
    license: licenses.cc0,
    source: "https://commons.wikimedia.org/wiki/File:Dominik_Szoboszlai_04012026_(1).jpg",
  },
  {
    slug: "florian-wirtz",
    name: "Wirtz",
    fullName: "Florian Wirtz",
    number: "07",
    position: "中场",
    role: "空间识别 · 创造核心",
    group: "中场",
    image: "/players/wirtz.jpg",
    photoPosition: "50% 14%",
    photoContext: "利物浦到场",
    credit: "Timmy96",
    license: licenses.cc0,
    source: "https://commons.wikimedia.org/wiki/File:Florian_Wirtz_04012026_(3).jpg",
  },
  {
    slug: "alexander-isak",
    name: "Isak",
    fullName: "Alexander Isak",
    number: "09",
    position: "前锋",
    role: "无球攻击 · 禁区终结",
    group: "锋线",
    image: "/players/isak.jpg",
    photoPosition: "50% 12%",
    photoContext: "国家队 · 过渡图",
    transitional: true,
    credit: "Rolandhino1",
    license: licenses.ccBySa,
    source: "https://commons.wikimedia.org/wiki/File:UEFA_EURO_qualifiers_Sweden_vs_Spain_20191015_Alexander_Isak_56_(cropped).jpg",
  },
  {
    slug: "bradley-barcola",
    name: "B. Barcola",
    fullName: "Bradley Barcola",
    number: "29",
    position: "边锋",
    role: "一对一 · 变速突破",
    group: "锋线",
    image: "/players/barcola.jpg",
    photoPosition: "57% 28%",
    photoContext: "利物浦签约照",
    credit: "Kvvin Nastreich",
    license: licenses.ccBySa,
    source: "https://commons.wikimedia.org/wiki/File:Bradley_Barcola_at_Liverpool_Signing_2026-2027_season.jpg",
  },
  {
    slug: "victor-munoz",
    name: "V. Muñoz",
    fullName: "Víctor Muñoz",
    number: "23",
    position: "边锋",
    role: "反复冲击 · 回防投入",
    group: "锋线",
    image: "/players/victor-munoz.jpg",
    photoPosition: "50% 18%",
    photoContext: "国家队 · 过渡图",
    transitional: true,
    credit: "Bryan Berlin / WikiPortraits",
    license: licenses.ccBySa,
    source: "https://commons.wikimedia.org/wiki/File:Victor_Munoz_France_v_Spain_7.24.26-017.jpg",
  },
];

export const rotationSquad: Player[] = [
  {
    slug: "giorgi-mamardashvili",
    name: "Mamardashvili",
    fullName: "Giorgi Mamardashvili",
    number: "25",
    position: "门将",
    role: "大体型覆盖 · 门线反应",
    group: "门将",
    image: "/players/rotation/mamardashvili.jpg",
    photoPosition: "50% 18%",
    photoContext: "利物浦比赛",
    credit: "Timmy96",
    license: licenses.cc0,
    source: "https://commons.wikimedia.org/wiki/File:Giorgi_Mamardashvili_04012026_(2).jpg",
  },
  {
    slug: "freddie-woodman",
    name: "Woodman",
    fullName: "Freddie Woodman",
    number: "28",
    position: "门将",
    role: "稳健站位 · 英式出球",
    group: "门将",
    image: "/players/rotation/woodman.jpg",
    photoPosition: "50% 16%",
    photoContext: "利物浦到场",
    credit: "Timmy96",
    license: licenses.cc0,
    source: "https://commons.wikimedia.org/wiki/File:Freddie_Woodman_04012026_(2).jpg",
  },
  {
    slug: "harvey-davies",
    name: "H. Davies",
    fullName: "Harvey Davies",
    number: "95",
    position: "门将",
    role: "青训门将 · 长传启动",
    group: "门将",
    image: "/players/rotation/harvey-davies.jpg",
    photoPosition: "50% 15%",
    photoContext: "利物浦到场",
    credit: "Timmy96",
    license: licenses.cc0,
    source: "https://commons.wikimedia.org/wiki/File:Harvey_Davies_06042025_(1).jpg",
  },
  {
    slug: "joe-gomez",
    name: "Gomez",
    fullName: "Joe Gomez",
    number: "02",
    position: "后卫",
    role: "多位置补位 · 回追速度",
    group: "防线",
    image: "/players/rotation/joe-gomez.jpg",
    photoPosition: "50% 15%",
    photoContext: "利物浦到场",
    credit: "Timmy96",
    license: licenses.cc0,
    source: "https://commons.wikimedia.org/wiki/File:Joe_Gomez_04012026_(1).jpg",
  },
  {
    slug: "jeremy-jacquet",
    name: "Jacquet",
    fullName: "Jérémy Jacquet",
    number: "05",
    position: "中卫",
    role: "正面防守 · 高空覆盖",
    group: "防线",
    image: "/players/rotation/jacquet.jpg",
    photoPosition: "50% 15%",
    photoContext: "雷恩时期 · 过渡图",
    transitional: true,
    credit: "Paté kroute",
    license: licenses.cc0,
    source: "https://commons.wikimedia.org/wiki/File:Jacquet_asse_srfc_2425.png",
  },
  {
    slug: "conor-bradley",
    name: "Bradley",
    fullName: "Conor Bradley",
    number: "12",
    position: "右后卫",
    role: "纵向冲刺 · 无球后插",
    group: "防线",
    image: "/players/rotation/bradley.jpg",
    photoPosition: "50% 15%",
    photoContext: "利物浦到场",
    credit: "Timmy96",
    license: licenses.cc0,
    source: "https://commons.wikimedia.org/wiki/File:Conor_Bradley_04012026_(1).jpg",
  },
  {
    slug: "kostas-tsimikas",
    name: "Tsimikas",
    fullName: "Kostas Tsimikas",
    number: "21",
    position: "左后卫",
    role: "边路输送 · 定位球质量",
    group: "防线",
    image: "/players/rotation/tsimikas.jpg",
    photoPosition: "50% 15%",
    photoContext: "利物浦到场",
    credit: "Timmy96",
    license: licenses.cc0,
    source: "https://commons.wikimedia.org/wiki/File:Kostas_Tsimikas_06042025_(1).jpg",
  },
  {
    slug: "ronald-araujo",
    name: "Araújo",
    fullName: "Ronald Araújo",
    number: "33",
    position: "中卫",
    role: "对抗侵略 · 大范围补防",
    group: "防线",
    image: "/players/rotation/araujo.jpg",
    photoPosition: "50% 13%",
    photoContext: "巴萨时期 · 过渡图",
    transitional: true,
    credit: "Werner100359",
    license: licenses.cc0,
    source: "https://commons.wikimedia.org/wiki/File:FC_Red_Bull_Salzburg_gegen_CF_Barcelona_(Testspiel_4._August_2021)_45_(cropped).jpg",
  },
  {
    slug: "wataru-endo",
    name: "Endo",
    fullName: "Wataru Endo",
    number: "03",
    position: "中场",
    role: "对抗拦截 · 节奏收束",
    group: "中场",
    image: "/players/rotation/endo.jpg",
    photoPosition: "50% 15%",
    photoContext: "利物浦到场",
    credit: "Timmy96",
    license: licenses.cc0,
    source: "https://commons.wikimedia.org/wiki/File:Wataru_End%C5%8D_06042025_(2).jpg",
  },
  {
    slug: "alexis-mac-allister",
    name: "Mac Allister",
    fullName: "Alexis Mac Allister",
    number: "10",
    position: "中场",
    role: "转身摆脱 · 线路组织",
    group: "中场",
    image: "/players/rotation/mac-allister.jpg",
    photoPosition: "50% 15%",
    photoContext: "利物浦到场",
    credit: "Timmy96",
    license: licenses.cc0,
    source: "https://commons.wikimedia.org/wiki/File:Alexis_Mac_Allister_04012026_(1).jpg",
  },
  {
    slug: "trey-nyoni",
    name: "Nyoni",
    fullName: "Trey Nyoni",
    number: "42",
    position: "中场",
    role: "接球朝前 · 青春创造",
    group: "中场",
    image: "/players/rotation/nyoni.jpg",
    photoPosition: "100% 50%",
    photoContext: "利物浦到场",
    credit: "Timmy96",
    license: licenses.cc0,
    source: "https://commons.wikimedia.org/wiki/File:Trey_Nyoni_04012026_(1).jpg",
  },
  {
    slug: "federico-chiesa",
    name: "Chiesa",
    fullName: "Federico Chiesa",
    number: "14",
    position: "边锋",
    role: "直接攻击 · 逆足射门",
    group: "锋线",
    image: "/players/rotation/chiesa.jpg",
    photoPosition: "50% 14%",
    photoContext: "利物浦到场",
    credit: "Timmy96",
    license: licenses.cc0,
    source: "https://commons.wikimedia.org/wiki/File:Federico_Chiesa_04012026_(1).jpg",
  },
  {
    slug: "cody-gakpo",
    name: "Gakpo",
    fullName: "Cody Gakpo",
    number: "18",
    position: "前锋",
    role: "左肋持球 · 内切终结",
    group: "锋线",
    image: "/players/rotation/gakpo.jpg",
    photoPosition: "50% 14%",
    photoContext: "利物浦到场",
    credit: "Timmy96",
    license: licenses.cc0,
    source: "https://commons.wikimedia.org/wiki/File:Cody_Gakpo_06042025_(1).jpg",
  },
  {
    slug: "hugo-ekitike",
    name: "Ekitike",
    fullName: "Hugo Ekitike",
    number: "22",
    position: "前锋",
    role: "移动支点 · 串联终结",
    group: "锋线",
    image: "/players/rotation/ekitike.jpg",
    photoPosition: "50% 13%",
    photoContext: "巴黎时期 · 过渡图",
    transitional: true,
    credit: "Liondartois",
    license: licenses.ccBySa,
    source: "https://commons.wikimedia.org/wiki/File:Hugo_Ekitike_(PSG_2023)_(cropped2).jpg",
  },
  {
    slug: "rio-ngumoha",
    name: "Ngumoha",
    fullName: "Rio Ngumoha",
    number: "73",
    position: "边锋",
    role: "一对一胆量 · 瞬间爆发",
    group: "锋线",
    image: "/players/rotation/ngumoha.jpg",
    photoPosition: "50% 13%",
    photoContext: "利物浦到场",
    credit: "Timmy96",
    license: licenses.cc0,
    source: "https://commons.wikimedia.org/wiki/File:Rio_Ngumoha_04012026_(1).jpg",
  },
];

export const rotationGroups = ["门将", "防线", "中场", "锋线"] as const;
